function updateFX(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-dt*3);p.vy*=Math.exp(-dt*3);if(p.life<=0)particles.splice(i,1);}for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.life-=dt;r.r=lerp(r.r,r.max,1-Math.exp(-dt*10));if(r.life<=0)rings.splice(i,1);}shake*=Math.exp(-dt*9);}
function drawGrid(){ctx.fillStyle='#070914';ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.16;ctx.strokeStyle='#3150a5';ctx.lineWidth=1;const s=44;for(let x=(time*12)%s;x<W;x+=s){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=(time*7)%s;y<H;y+=s){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}ctx.restore();const g=ctx.createRadialGradient(W*.5,H*.5,60,W*.5,H*.5,Math.max(W,H)*.65);g.addColorStop(0,'rgba(45,24,90,.18)');g.addColorStop(1,'rgba(0,0,0,.55)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
function drawObstacle(o){if(o.dead)return;ctx.save();ctx.translate(o.x,o.y);const c=o.kind==='explosive'?'#ff735f':o.kind==='reinforced'?'#a286ff':'#788cff';ctx.fillStyle='rgba(18,24,45,.92)';ctx.strokeStyle=c;ctx.lineWidth=2;ctx.shadowBlur=12;ctx.shadowColor=c;ctx.fillRect(-o.w/2,-o.h/2,o.w,o.h);ctx.strokeRect(-o.w/2,-o.h/2,o.w,o.h);ctx.globalAlpha=.2;for(let x=-o.w/2+10;x<o.w/2;x+=18){ctx.beginPath();ctx.moveTo(x,-o.h/2);ctx.lineTo(x-12,o.h/2);ctx.stroke();}ctx.globalAlpha=.75;ctx.fillStyle=c;ctx.fillRect(-o.w/2,o.h/2-3,o.w*(o.hp/o.maxHp),3);ctx.restore();}
function drawMage(m){if(!m.alive)return;const fade=clamp(m.boss2WarpAlpha??1,0,1);ctx.save();ctx.globalAlpha=fade;ctx.translate(m.x,m.y);ctx.rotate(m.aim);ctx.shadowBlur=m.type==='boss'?40:24;ctx.shadowColor=m.color;ctx.strokeStyle=m.color;ctx.fillStyle='rgba(10,14,30,.95)';ctx.lineWidth=m.type==='boss'?4:3;const sides=m.type==='boss'?8:6;ctx.beginPath();for(let i=0;i<sides;i++){const a=i*Math.PI*2/sides,r=m.r*(i%2?.78:1),x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(m.r*.45,-m.r*.25);ctx.lineTo(m.r*1.55,0);ctx.lineTo(m.r*.45,m.r*.25);ctx.closePath();ctx.fillStyle=m.color;ctx.globalAlpha=fade*.75;ctx.fill();ctx.globalAlpha=fade;ctx.rotate(-m.aim);ctx.globalAlpha=fade*.28;ctx.beginPath();ctx.arc(0,0,m.r+7+Math.sin(time*5+m.phase)*2,0,Math.PI*2);ctx.stroke();if((m.shield||0)>0||(m.tempShield||0)>0){ctx.globalAlpha=fade*((m.tempShield||0)>0?.9:.5);ctx.strokeStyle='#7de7ff';ctx.lineWidth=(m.tempShield||0)>0?4:2;ctx.shadowBlur=28;ctx.shadowColor='#7de7ff';ctx.beginPath();ctx.arc(0,0,m.r+15+Math.sin(time*7)*2,0,Math.PI*2);ctx.stroke();}ctx.restore();}
function drawPickup(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.spin);const c=p.type==='red'?'#ff405f':p.type==='purple'?'#bd6bff':p.type==='green'?'#58ff89':p.type==='excalibur'?'#ffd86b':p.type==='fortress'?'#76fff0':'#4da3ff';ctx.shadowBlur=30;ctx.shadowColor=c;ctx.fillStyle='rgba(8,12,28,.92)';ctx.strokeStyle=c;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.globalAlpha=.75;ctx.beginPath();ctx.arc(0,0,p.r*.55,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.9;ctx.fillStyle=c;ctx.beginPath();ctx.arc(0,0,p.r*.22,0,Math.PI*2);ctx.fill();
 if(p.type==='excalibur'){ctx.globalAlpha=1;ctx.strokeStyle=c;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-p.r*.72);ctx.lineTo(0,p.r*.48);ctx.moveTo(-p.r*.28,-p.r*.18);ctx.lineTo(p.r*.28,-p.r*.18);ctx.stroke();}
 if(p.type==='purple'){ctx.globalAlpha=.9;ctx.fillStyle=c;ctx.fillRect(-p.r,p.r+7,(p.r*2)*clamp((p.hp||0)/(p.maxHp||125),0,1),3);}
 if(p.type==='fortress'){ctx.globalAlpha=1;ctx.strokeStyle=c;ctx.lineWidth=3;ctx.strokeRect(-p.r*.34,-p.r*.34,p.r*.68,p.r*.68);}
 ctx.restore();}
function playerShotHiddenInBoss2Aura2(b){const boss=enemies.find(e=>e.alive&&e.boss2&&e.auraEffect===2);if(!boss)return false;const playerShot=b.playerShot===true||b.owner===player||b.owner===remotePlayer;if(!playerShot)return false;return Math.hypot(b.x-boss.x,b.y-boss.y)<=boss.auraRadius;}
function drawBullet(b){if(playerShotHiddenInBoss2Aura2(b))return;ctx.save();ctx.translate(b.x,b.y);ctx.shadowBlur=b.blast?26:16;ctx.shadowColor=b.color;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(0,0,b.r*(1+.12*Math.sin(b.pulse)),0,Math.PI*2);ctx.fill();ctx.globalAlpha=.35;ctx.beginPath();ctx.moveTo(-b.vx*.03,-b.vy*.03);ctx.lineTo(0,0);ctx.strokeStyle=b.color;ctx.lineWidth=b.blast?10:5;ctx.stroke();ctx.restore();}
function drawFX(){for(const r of rings){ctx.save();ctx.globalAlpha=clamp(r.life/.4,0,1);ctx.strokeStyle=r.color;ctx.lineWidth=3;ctx.shadowBlur=18;ctx.shadowColor=r.color;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke();ctx.restore();}for(const p of particles){ctx.save();ctx.globalAlpha=clamp(p.life/.7,0,1);ctx.fillStyle=p.color;ctx.shadowBlur=12;ctx.shadowColor=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size*clamp(p.life/.35,0,1),0,Math.PI*2);ctx.fill();ctx.restore();}}
function drawArenaBoundary(){const ab=arenaBounds(),delay=shrinkDelayForStage(),shrinking=state==='battle'&&delay!=null&&time>delay;ctx.save();ctx.fillStyle=shrinking?'rgba(40,0,18,.58)':'rgba(0,0,0,.52)';ctx.fillRect(0,0,W,ab.top);ctx.fillRect(0,ab.bottom,W,H-ab.bottom);ctx.fillRect(0,ab.top,ab.left,ab.h);ctx.fillRect(ab.right,ab.top,W-ab.right,ab.h);ctx.strokeStyle=shrinking?'rgba(255,65,105,.98)':'rgba(100,180,255,.7)';ctx.lineWidth=shrinking?6:4;ctx.shadowBlur=shrinking?30:20;ctx.shadowColor=ctx.strokeStyle;ctx.strokeRect(ab.left,ab.top,ab.w,ab.h);if(shrinking){ctx.globalAlpha=.28;ctx.lineWidth=14;ctx.strokeRect(ab.left+5,ab.top+5,Math.max(0,ab.w-10),Math.max(0,ab.h-10));}ctx.restore();}
function drawBoss2Aura(){const b=enemies.find(e=>e.alive&&e.boss2);if(!b||!b.auraColors)return;const c=b.auraColors[b.auraIndex]||'#ffffff';ctx.save();ctx.translate(b.x,b.y);ctx.globalAlpha=.07;ctx.fillStyle=c;ctx.beginPath();ctx.arc(0,0,b.auraRadius,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.5;ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,b.auraRadius,0,Math.PI*2);ctx.stroke();if((b.auraPulseT||0)>0){ctx.globalAlpha=.85*(1-b.auraPulse);ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,b.auraRadius*clamp(b.auraPulse,0,1),0,Math.PI*2);ctx.stroke();}ctx.restore();}

function draw(){ctx.save();ctx.translate(rand(-shake,shake),rand(-shake,shake));drawGrid();drawArenaBoundary();drawBoss2Aura();for(const o of obstacles)drawObstacle(o);for(const p of pickups)drawPickup(p);for(const b of bullets)drawBullet(b);drawFX();if(player)drawMage(player);if(remotePlayer&&remotePlayer!==player)drawMage(remotePlayer);for(const e of enemies){if(!(player&&(player.invisibleEnemyT||0)>0))drawMage(e);}if(player&&(player.forcedAimT||0)>0){ctx.save();ctx.strokeStyle='#9bc7ff';ctx.lineWidth=3;ctx.globalAlpha=.95;ctx.beginPath();ctx.arc(player.forcedAimX,player.forcedAimY,16,0,Math.PI*2);ctx.moveTo(player.forcedAimX-24,player.forcedAimY);ctx.lineTo(player.forcedAimX+24,player.forcedAimY);ctx.moveTo(player.forcedAimX,player.forcedAimY-24);ctx.lineTo(player.forcedAimX,player.forcedAimY+24);ctx.stroke();ctx.restore();}ctx.restore();}
function effectText(m){
 if(!m)return'';
 const parts=[];
 if(m.effect){
   const n={speedBuff:'이동 가속',fireBuff:'연사 가속',speedDebuff:'이동 저하',fireDebuff:'연사 저하',homingBuff:'유도탄',shieldBuff:'실드 +25%'}[m.effect];
   if(n)parts.push(`${n} ${m.effectT.toFixed(1)}s`);
 }
 if((m.attackDebuffT||0)>0)parts.push(`공격력 50% ${(m.attackDebuffT).toFixed(1)}s`);
 if((m.specialLockT||0)>0)parts.push(`특수탄 봉인 ${(m.specialLockT).toFixed(1)}s`);
 if((m.invisibleEnemyT||0)>0)parts.push(`적군 은폐 ${(m.invisibleEnemyT).toFixed(1)}s`);
 if((m.deferredDebuffT||0)>0)parts.push(`집행유예 x${m.deferredDebuffStacks||1} ${(m.deferredDebuffT).toFixed(1)}s`);
 if((m.excaliburT||0)>0)parts.push(`엑스칼리버 ${(m.excaliburT).toFixed(1)}s`);
 if((m.fortressShieldDecay||0)>0&&m.maxShield>0&&m.shield>m.maxShield)parts.push(`요새 실드 ${Math.round(m.shield/m.maxShield*100)}%`);
 return parts.length?' · '+parts.join(' · '):'';
}
function updateUI(){if(!player)return;document.getElementById('pfill').style.width=clamp(player.health/player.maxHealth*100,0,100)+'%';const alive=enemies.filter(e=>e.alive),sumMax=enemies.reduce((a,e)=>a+e.maxHealth,0)||1,sumHp=enemies.reduce((a,e)=>a+Math.max(0,e.health),0);document.getElementById('afill').style.width=clamp(sumHp/sumMax*100,0,100)+'%';document.getElementById('pstat').textContent=`HP ${Math.ceil(player.health)}/${Math.ceil(player.maxHealth)} · SH ${Math.ceil(player.shield||0)}/${Math.ceil(player.maxShield||0)}${(player.tempShield||0)>0?` +${Math.ceil(player.tempShield)} TEMP`:''} · CR ${run.credits} · 폭발 ${run.up.blast>0?`1/${novaInterval()}`:'LOCKED'} · 유도 ${run.up.homing>0?`1/${homingInterval()}`:'LOCKED'}${effectText(player)}`;document.getElementById('astat').textContent=`잔존 ${alive.length}/${enemies.length} · HP ${Math.ceil(sumHp)}/${Math.ceil(sumMax)}`;document.getElementById('enemyName').textContent=stageType(Math.max(1,run.stage-(state==='shop'?0:0)))==='bigBoss'?'TITAN NOVA':stageType(Math.max(1,run.stage))==='midBoss'?'GUARDIAN // NOVA':'NOVA // SQUAD';{const ab=arenaBounds(),shrinkDelay=shrinkDelayForStage(),arenaText=state==='battle'?(shrinkDelay==null?' · ARENA FIXED':time<shrinkDelay?` · 축소 ${Math.ceil(shrinkDelay-time)}s`:` · ARENA ${Math.round(ab.w)}×${Math.round(ab.h)}`):'';document.getElementById('stagePanel').textContent=`${multiplayer.mode==='vs'?'DUEL // VS':stageLabel(run.stage)} · ${run.credits} CR${remotePlayer&&remotePlayer!==player?` · P2 ${Math.max(0,Math.ceil(remotePlayer.health||0))}HP`:''}${arenaText}`;}if(messageTimer>0){messageTimer-=1/60;if(messageTimer<=0)document.getElementById('centerMsg').style.opacity=0;}}
